// www.phantom/src/view/Home.vue
<template>
	<div>
		<h1>Hello world!</h1>
	</div>
</template>

<script>
	import api from '@/service/safe/api';

	export default {
		name: 'Sidebar',
		mounted: function () {
			api.authenticate().then(response => {
				this.$root.$data.authenticated = response;
			});
		},
	}
</script>

<style lang="scss">
	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 4em;
		font-weight: 100;
	}
</style>

// www.phantom/src/views/Home.svelte
<main>
	<h1>Hello world!</h1>
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 4em;
		font-weight: 100;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>
